### ISSUE TITLE
Hamburger-Icon

### ISSUE THREAD

**Issue by Rishit30G** [Rishit30G/Personal-Portfolio#26]
This issue is for @0rGaan1c ( Chetan Sagar ) 
Just make sure you host it online, so that I can see the changes clearly

**Comment by 0rGaan1c** [comment]
Alright, I will start working on it, I have one question tho. Should I remove the font-awesome icon(because we need a kit code for that) and create a new one using just HTML and CSS (like I did before)?

**Comment by Rishit30G** [comment]
Just make sure that you don't make your Web-kit key public, though there is no problem or anything for this particular one, but if possible avoid it! 
And If you make a new one, just make sure there is no problem like ( Incase some new user uses this portfolio for his/her work and then uses his personal Web-Kit key and multiple icons pop up ) 
I hope this makes sense, you can contact me further on this issue

**Comment by 0rGaan1c** [comment]
So, I just run the website on my local machine and put my web-kit key in 
` <script src="https://kit.fontawesome.com/{{YOUR KIT KEY}}.js" crossorigin="anonymous"></script>` and its working, and there isn't an issue with it, but we can't see the icon on the hosted URL because we have to put a kit key in the Github repository.
And, if someone uses this portfolio for their work and they put in their kit key it will work.

One thing that we can do is, remove the font-awesome icon and make a new one so that whoever uses the portfolio doesn't have to worry about putting their kit key in it and the icon will also be visible on the hosted website. 
What will be a good thing to do here?

**Comment by Rishit30G** [comment]
Ok! 
So that would mean plenty of changes in the file for all the icons, I would not approve that, since it could lead to multiple errors 
If you could find some other way of just like having separate icons for the "cross" and "hamburger", that would be appreciated!
